---
  db:
    url: "{{_vault['db']['url']}}"
    user: "{{_vault['db']['user']}}"
    password: "{{_vault['db']['password']}}"

  github:
    client_id: "{{_vault['github']['client_id']}}"
    client_secret: "{{_vault['github']['client_secret']}}"

  metrics:
    graphite:
      host: "{{_vault.metrics.graphite.host}}"
    grafana:
      api_key: "{{_vault.metrics.grafana.api_key}}"

  slack:
    legacyToken: "{{_vault.slack.legacyToken}}"
